version: '3.8'

services:
  product-service:
    build: 
      context: ./product_service

  discount-service:
    build: 
      context: ./discount_service

  order-service:
    build: 
      context: ./order_service
    ports:
      - "8002:8000" 
    environment:
      - PRODUCT_SERVICE_URL=http://product-service:8000
      - DISCOUNT_SERVICE_URL=http://discount-service:8000
    depends_on:
      - product-service
      - discount-service