services:
  product-service:
    build: ./product_service  
    ports:
      - "8001:8000"
    networks:
      - service-net

  # discount-service:
  #   build: ./discount-service  
  #   ports:
  #     - "8003:8000"
  #   networks:
  #     - service-net

  order-service:
    build: ./order_service    
    ports:
      - "8002:8000"
    environment:
      - PRODUCT_SERVICE_URL=http://product-service:8000
      - DISCOUNT_SERVICE_URL=http://discount-service:8000
    depends_on:
      - product-service
      - discount-service
    networks:
      - service-net

  redis:
    image: redis:alpine
    container_name: redis-cache
    networks:
      - service-net
    ports:
      - "6379:6379" 

  discount-service:
    build: ./discount-service
    container_name: discount-service
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379 
    networks:
      - service-net
    depends_on:
      - redis 

networks:
  service-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.10.0/24