create-structure:
	mkdir src test docs
	touch README.md setup.py requirements.txt
	touch docs/DOMAIN.md
	touch docs/SPECIFICATION.md
	touch src/.gitkeep tests/.gitkeep
	
install-dep:
	pip install -r requirements.txt

install:
	pip install -e

test-pytest:
	python3 -m pytest



	