[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ndfl-calculator-toolkit"
version = "0.1.0"
description = "Tool for work with NDFL"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[project.urls]
Homepage = "https://github.com/Turik06/test-git-fossdev/tree/hw_pypi"