# pyproject.toml

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ndfl-turik" 
version = "0.1.0"
description = "Расчет НДФЛ по прогрессивной шкале с 2025 года"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest",
    "build",
    "twine"
]

[tool.setuptools.packages.find]
where = ["src"]